Planner/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login1/', auth_views.LoginView.as_view(template_name='users/login1.html'), name='login1'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('login.urls')),
     path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
# login/urls.py

from django.urls import path
from .views import (
    home,
    about,
    destinations,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    like_post, 
    CommentCreateView,
    CommentUpdateView,
    comment_delete,
)
from . import views

urlpatterns = [
    path('', home, name='login-home'),  
    path('posts/', PostListView.as_view(), name='login-post'), 
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='login-about'),
    path('post/<int:pk>/like/', like_post, name='like-post'),
    path('destinations/', views.destinations, name='login-destinations'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='comment-create'),
    path('post/<int:pk>/comment/', CommentCreateView.as_view(), name='comment-create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
   path('comment/<int:pk>/delete/', comment_delete, name='comment-delete'),


]

users/urls.py
from django.urls import path, include
from .views import TaskListView, TaskCreate, TaskUpdate, DeleteView
from .views import ItineraryListView, ItineraryCreate, ItineraryUpdate
from . import views
from django.urls import re_path

app_name = 'users'
urlpatterns = [
     path('task_list/', TaskListView.as_view(), name='task_list'),
     path('task-create/', TaskCreate.as_view(), name='task-create'),
     path('task-update/<int:pk>', TaskUpdate.as_view(), name='task-update'),
     path('task-delete/<int:pk>', DeleteView.as_view(), name='task-delete'),
     path('task_list/', ItineraryListView.as_view(), name='itinerary_list'),
     path('itinerary-create/', ItineraryCreate.as_view(), name='itinerary-create'),
     path('itinerary-update/', ItineraryUpdate.as_view(), name='itinerary-update'),
   
     path('calendar/', views.CalendarView.as_view(), name='calendar'),
     path('event/new/', views.event, name='event_new'),
      re_path(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

login/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


    
class CustomUser(models.Model):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.author.username} - {self.post.title}'
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    comments = models.ManyToManyField(Comment, related_name='post_comments', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from .observers import TaskCompletionNotifier
from .observers import TaskCompletionObserver
from django.db.models.signals import post_save
from django.dispatch import receiver
#from .models import Task



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


from django.db import models
from .observers import TaskCompletionNotifier, TaskCompletionObserver

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) 
    title = models.CharField(max_length=200) 
    complete = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()  
    @property
    def get_html_url(self):
        url = reverse('users:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'      
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        if self.complete:
            notifier = TaskCompletionNotifier()
            notifier.attach(TaskCompletionObserver()) 
            notifier.notify_observers(self)


class Itinerary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) 
    title = models.CharField(max_length=200) 

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .models import Event
from django.forms import ModelForm, DateInput

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

users/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic.list import ListView
from .models import Task, Itinerary
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .observers import TaskCompletionObserver
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

task_observer = TaskCompletionObserver()

from django.views.generic import ListView

from .models import *
from .utils import Calendar
from datetime import datetime
from django.utils.safestring import mark_safe
from datetime import timedelta
import calendar
from .utils import Calendar  # Adjust the import path based on your project structure
from .forms import EventForm
from datetime import date  # Import the date module


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login1')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'users/task_list.html'  
    context_object_name = 'tasks'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['itinerary'] = Itinerary.objects.filter(user=self.request.user)
        return context

   
class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title','complete']
    success_url = reverse_lazy('users:task_list')
    
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(TaskCreate,self).form_valid(form)
    
    
class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'tasks'
    success_url = reverse_lazy('users:task_list')
    
class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title','complete']
    success_url = reverse_lazy('users:task_list')

class CalendarView(ListView):
    model = Event
    template_name = 'users/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('day', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        
        d = get_date(self.request.GET.get('month', None))
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('users:calendar'))
    return render(request, 'users/event.html', {'form': form})

    def form_valid(self, form):
        if 'complete' in self.request.POST:
            task = form.save(commit=False)
            task.complete = True
            task.save()
        else:
            form.save()
        return super().form_valid(form)
    
class ItineraryListView(LoginRequiredMixin, ListView):
    model = Itinerary
    template_name = 'users/task_list.html'  
    context_object_name = 'itinerary'
    
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['itinerary']=context['itinerary'].filter(user=self.request.user)
        return context


class ItineraryCreate(LoginRequiredMixin, CreateView):
    model = Itinerary
    fields = ['title']
    success_url = reverse_lazy('users:itinerary_list')
    
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(ItineraryCreate,self).form_valid(form)
    
    
class ItineraryUpdate(LoginRequiredMixin, UpdateView):
    model = Itinerary
    fields = ['title']
    success_url = reverse_lazy('users:itinerary_list')


users/templates/users/base.html
{'% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{'% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {'% block content %}
  {'% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {'% block script %}
  {'% endblock %}
</body>
</html>

users/templates/users/calendar.html
{% extends "login/base.html" %}
{% load static %}
{% block content %}

<div class="left-side-image">
    <img src="{% static 'images/cherryblossom.jpeg' %}" alt="Descriptive Alt Text">
</div>

<div class="content-container">
        <a class="btn btn-info left" href="{% url 'users:calendar' %}?{{ prev_month }}">Previous Month</a>
        <a class="btn btn-info right" href="{% url 'users:calendar' %}?{{ next_month }}">Next Month</a>

    <div class="calendar-container">
        {{ calendar }} {# This will display the calendar HTML generated in your view #}
    </div>
</div>

<style>
    html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
        overflow-x: hidden;
    }

    .left-side-image {
        position: fixed;
        top: 0;
        left: 0;
        width: 37%; /* Cover half of the screen */
        height: 100%;
        overflow: hidden;
        z-index: -1;
    }

    .left-side-image img {
        height: 100%;
        width: 100%;
        object-fit: cover; /* Ensure the image covers the entire div */
    }

    .content-container {
        margin-left: 5%; /* Start the content from the middle of the screen */
        width: -20%; /* Use the right half of the screen */
        height: 100vh;
        overflow-y: auto;
    }

    .calendar-container {
        width: 100%;
        margin: auto;
        padding: 1%;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .calendar tr,
    .calendar td {
        border: 1px solid black;
    }

    .calendar th {
        padding: 10px;
        text-align: center;
        font-size: 18px;
    }

    .calendar td {
        width: 200px;
        height: 150px;
        padding: 20px 0px 0px 5px;
    }

    .month {
        font-size: 25px;
    }



    ul {
        height: 100%;
        padding: 0px 5px 0px 20px;
    }

    a {
        color: #17a2b8;
    }


    a:hover {
        text-decoration: underline;
    }
</style>


{% endblock %}

users/templates/users/event.html
{% extends 'users/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'users:calendar' %}">Calendar</a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form.as_table }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right">Submit</button></td></tr>
  </table>
</form>
{% endblock %}

users/templates/users/itinerary_form.html
{% extends "login/base.html" %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right, #dbceeb, #87cefa);
        margin-left: 50px;
        margin-top: 100px;
        overflow-x: hidden;
    }
    .form-container {
        border: 2px solid #ddd;
        padding: 15px; /* Reduced padding */
        background-color: rgba(255, 255, 255, 0.6);
        width: 50%; /* Adjust width as needed */
        margin: 0 auto; /* Center the form */
        margin-bottom: 20px;
        border-radius: 15px; /* Increased border-radius for rounder corners */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Optional: added a subtle shadow */
    }
    input[type="submit"] {
        background-color: #007bff;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    input[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>
    <div class="form-container">
<h3>itinerary form</h1>
<a href="{%url 'users:itinerary_list' %}">Go back</a>
<form method="POST" action="">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
</div>
{% endblock content %}

users/templates/users/login1.html
{% extends "login/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="full-screen-bg">
    <!-- Full Screen Background Image -->
    <div class="background-image-container" style="background-image: url('/static/images/loginbackground.jpg');"></div>

    <!-- Login Container -->
    <div class="login-container">
        <!-- Text Content Section -->
        <div class="text-content-section">
            <!-- Your form code here -->
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 font-weight-bold">Log In</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                    <small class="text-muted ml-2">
                        <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </div>
            </form>
            <div>
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
                </small>
            </div>
        </div>

        <!-- Login Image Container -->
        <div class="login-image-container">
            <img src="/static/images/login.jpg" alt="Login Image" />
        </div>
    </div>
    <style>
        html,
        body {

            overflow: hidden;
            /* Prevent scrolling */

        }
    </style>
</div>

<div class="full-screen-bg">
    <!-- Full Screen Background Image -->
    <div class="background-image-container" style="background-image: url('/static/images/loginbackground.jpg');"></div>

    <!-- Login Container -->
    <div class="login-container">
        <!-- Text Content Section -->
        <div class="text-content-section">
            <!-- Your form code here -->
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 font-weight-bold">Log In</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Login</button>
                </div>
            </form>
            <div>
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
                </small>
            </div>
        </div>

        <!-- Login Image Container -->
        <div class="login-image-container">
            <img src="/static/images/login.jpg" alt="Login Image" />
        </div>
    </div>
    <style>
        html,
        body {
            overflow: hidden;
            /* Prevent scrolling */
        }
    </style>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends "login/base.html" %}
{% load crispy_forms_tags %}

{% block sidebar %}
{# Empty block to exclude the sidebar #}
{% endblock sidebar %}

{% block content %}
<style>
  html,
  body {
    overflow: hidden;
    /* Prevent scrolling */
  }

  .background-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #A8C2DB;
    z-index: -1;
    /* Ensure the background is behind other elements */
  }

  .media {
    position: relative;
    /* Other styles... */
  }

  .account-info {
    text-align: left;
    margin-top: -100px;
  }

  .account-info h2 {
    font-size: 40px;
    font-weight: bold;
  }

  .account-info p {
    font-size: 20px;
  }


  .account-img {
    position: absolute;
    top: 200px;
    /* Adjust this value to move the image higher */
    right: -400px;
    /* Adjust this value to move the image to the left */
    margin-top: -350px;
    /* Negative value to move it higher */
    margin-left: -100px;
    /* Negative value to move it to the left */
  }

  .edit-profile-btn {
    position: absolute;
    top: 150%;
    right: -140%;
    transform: translate(-50%, 0);
    margin-top: 20px;
    /* Adjust the margin as needed */
  }

  .user-posts {
    margin-top: 20px;
    /* Adjust the margin as needed */
    font-size: 20px;
    font-weight: bold;
  }

  .user-posts a {
    text-decoration: none;
    color: #333;
  }
</style>


<div class="background-container"></div>

<div class="content-section">
  <div class="account-info">
    <h2>{{ user.username }}</h2>
    <p class="text-secondary">{{ user.email }}</p>
  </div>

  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <button type="button" class="btn btn-outline-info edit-profile-btn" data-toggle="modal"
        data-target="#updateProfileModal">
        Edit Profile
      </button>


      <div class="user-posts">
        <h2>User's Posts:</h2>
        <ul>
          {% for post in user.post_set.all %}
          <li><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>


  <!-- Modal -->
  <div class="modal fade" id="updateProfileModal" tabindex="-1" role="dialog" aria-labelledby="updateProfileModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateProfileModalLabel">Update Profile</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

users/templates/users/task_list.html
{% extends "login/base.html" %}
{% block content %}
<style>
    body {
      background: linear-gradient(to right, #dbceeb , #87cefa);
      min-height: 10vh;
      margin-top: 30px;
    }
</style>
    <p>{{request.user}}</p>

    <!-- Container for Task List, Image and Itinerary List -->
    <div style="display: flex; justify-content: center; align-items: start; padding: 50px;margin-left:200px">
<style>
    body,html{
        overflow: hidden;
    }
</style>
        <!-- Task List -->
        <div style="width: 300px; height: 100px;">
            <div style="color: black; font-size: 24px; font-family: Inter; font-weight: 400; line-height: 24px; word-wrap: break-word">YOUR TO DO LIST</div>
            {% for task in tasks %}
                <div style="height: 67px; background: #800080; border-radius: 30px; display: flex; align-items: center; justify-content: center; margin-top: 15px;">
                    <p style="color: white;padding:5px">{{ task.title }}</p>
                    <a href="{% url 'users:task-update' pk=task.pk %}" style="color: white; text-decoration: none;padding:5px">Edit</a>
                    <form method="post" action="{% url 'users:task-delete' task.id %}">
                        {% csrf_token %}
                        <button type="submit" style="background-color: transparent; color: red; border: none; cursor: pointer;padding:5px">Delete</button>
                    </form>
                    <form method="post" action="{% url 'users:task-update' pk=task.pk %}" onsubmit="return confirm('Task marked as complete: {{ task.title }}')">
                    <form method="post" action="{% url 'users:task-update' pk=task.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="complete" value="True"> 
                        <button type="submit" style="background-color: transparent; color: green; border: none; cursor: pointer;padding:5px">Done</button>
                    </form>
                </div>
            {% empty %}
                <h3>No tasks yet.</h3>
            {% endfor %}
            <a href="{% url 'users:task-create' %}" style="display: inline-block; margin-top: 20px; color: #800080; text-decoration: none; border: 2px solid purple; padding: 10px; border-radius: 30px;">Add Task</a>
        </div>

        <!-- Image -->
        <div>
            <img src="https://png.pngtree.com/png-clipart/20230511/ourmid/pngtree-isolated-cat-on-white-background-png-image_7094927.png"/>
        </div>

        <!-- Itinerary List -->
        <div style="width: 321px; height: 437px;">
            <div style="color: black; font-size: 24px; font-family: Inter; font-weight: 400; line-height: 24px; word-wrap: break-word">YOUR ITINERARY</div>
            {% for item in itinerary %}
                <div style="height: 67px; background: #800080; border-radius: 30px; display: flex; align-items: center; justify-content: center; margin-top: 10px;">
                    <p style="color: white;">{{ item.title }}</p>
                </div>
            {% empty %}
                <h3>No itineraries yet.</h3>
            {% endfor %}
            <a href="{% url 'users:itinerary-create' %}" style="display: inline-block; margin-top: 20px; color: #2196F3; text-decoration: none;">Add Location</a>
        </div>        
    </div>
{% endblock content%}